# Generated by Django 2.1.3 on 2018-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='editor',
            field=models.TextField(default='hello', max_length=100),
        ),
    ]
