# Generated by Django 2.1.3 on 2018-12-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_question_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='editor',
            field=models.TextField(default='hello', max_length=10),
        ),
    ]
