# Generated by Django 2.1.3 on 2018-12-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_auto_20181211_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.TextField(default='Question 0', max_length=10),
        ),
    ]
