# Generated by Django 2.1.3 on 2018-12-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
    ]
